pytest-dev/pytest-asyncio

pytest_asyncio/plugin.py, tests/test_simple.py
- Inspired on the default implementation for pytest_pyfunc_call for normal test functions
- Refactor pytest_pyfunc_call to remove duplication
fixes #5
(BTW @Tinche, hope you don't mind me creating a branch in this repository instead of on a fork... let me know if you prefer the latter).
=> Add support for test methods

tests/test_simple.py
Fetching data from http://httpbin.org makes tests execution slow.
What we really need is checking for asyncio functionality, not HTTP page fetching.
=> Get rid of using external resource in tests

.travis.yml, pytest_asyncio/plugin.py, setup.py, tests/test_simple_35.py, tox.ini
PEP 492 added support for defining coroutines using `async def` rather
than having to decorate the function with `@asyncio.coroutine`. The new
`_is_coroutine` function will match any coroutines created with the
decorator using `inspect.isgeneratorfunction` as well as those created
through the async and await syntax using `asyncio.iscoroutinefunction`.
The tests for this need to be added in an unconventional way. `async`
and `await` cause syntax errors in versions of Python prior to 3.5.
Rather than causing the tests for 3.3 and 3.4 to fail, the tests are
being defined as a string and then compiled and executed into the
module. If a time ever comes that this library no longer supports
versions prior to 3.5, this new module can be removed entirely.
=> Support coroutines with async and await syntax

pytest_asyncio/plugin.py, tests/test_non_global_loop.py
I'm working on a project that aims not to depend on the implicit global loop; that is, if a client developer [explicitly passes an event loop instance][PEP3156] to classes and functions in this package, only that loop will be used.
Because many other packages, including `asyncio` itself, will get the default loop when not passed an instance explicitly, we would like to run our tests against a non-global loop instance to enforce this requirement.
To that end, I tried overriding the `event_loop` fixture, but I found that the pytest-asyncio marker is implicitly retrieving the default event loop via the call to `asyncio.async`. This proposed change simply passes `event_loop` explicitly to `asyncio.async`.
I wrote the corresponding test in its own module so that I could override the …
=> Make it possible to avoid using the global loop

README.rst, pytest_asyncio/plugin.py, setup.py, test_requirements.txt, tests/async_fixtures/test_async_gen_fixtures_35.py
This lets developers use async generator fixtures on Python 3.5 too.
=> Added support for the async_generator library

.travis.yml, setup.cfg, setup.py, test_requirements.txt, tox.ini
Mostly cosmetic simplifications and improvements in the testing and packaging setup.
Highlights:
* Use pytest-cov for test coverage
* Removed test_requirements.txt in favor of a `testing` extras (`pip install -e .[testing]`)
* Added `python_requires` to packaging metadata
* Use Pathlib for reading file contents
=> Packaging and testing cleanups

pytest_asyncio/plugin.py, tests/test_simple.py
Solves this:
- https://github.com/pytest-dev/pytest-asyncio/issues/52
And this:
- https://github.com/aio-libs/aiohttp/issues/1069
Now pytest-asyncio and pytest-aiohttp can act together with this conftest.py:
```python
from aiohttp.test_utils import loop_context
@pytest.yield_fixture
def loop():
with loop_context() as _loop:
yield _loop
@pytest.yield_fixture
def event_loop(loop):
yield loop
```
=> handle case when no event loop exists (support pytest-aiohttp)

.travis.yml, README.rst, pytest_asyncio/plugin.py, setup.py, tests/async_fixtures/test_coroutine_fixtures.py, tests/conftest.py, tests/multiloop/test_alternative_loops.py, tests/test_dependent_fixtures.py, tests/test_simple.py, tests/test_simple_35.py, tests/test_subprocess.py, tox.ini
- Enable tests and declare support for Python 3.7
- Use `async` and `await` in all tests
-  Remove ProcessPoolExecutor support
Remove the `event_loop_process_pool` fixture and the
`pytest.mark.asyncio_process_pool` marker to address deprecation and
removal detailed in https://bugs.python.org/issue34075.
Fixes #87.
~Note: this change may be blocked by #87. The behavior of the
`ProcessPoolExecutor` tests is somewhat flaky in 3.7 and may cause the
test suite to hang.~
Because this change is blocked by #87, I've rolled the fix into this PR.
I can split this up if desired.
=> Python 3.7 support

pytest_asyncio/plugin.py, setup.cfg, tests/test_simple.py, tox.ini
Pytest added a deprecation warning to signal fixtures being called
directly as functions.
Ref: https://github.com/pytest-dev/pytest/issues/3661
Ref: https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly
=> Fix: Avoid warning on latest Pytest versions

.gitignore, README.rst, pytest_asyncio/plugin.py, setup.py, tests/test_hypothesis_integration.py
=> Support async tests which use Hypothesis

pytest_asyncio/plugin.py
Closes #104
Tests still pass - am I missing anything?
=> Remove transfer_markers

pytest_asyncio/plugin.py, tests/test_hypothesis_integration.py
Async test functions marked for execution by Hypothesis are currently wrapped in a synchronous function during the test discovery phase of pytest. At this point, the `event_loop` fixture provided by pytest-asyncio has not been evaluated and the wrapper is forced to create a new loop for each hypothesis test. This may result is problems when using async-related code in fixtures as in #117.
This PR moves the wrapping code to the actual test execution. At this point the `event_loop` fixture is evaluated and there is no need to create a new loop for the test.
What's missing from this PR is a proper automated test case. Since I have run into this issue using aiohttp, I was using the following code to test it:
```python
import aiohttp
import pytest
from hypothesis import given
from …
```
=> Sync wrapper for hypothesis tests uses the event loop provided by pytest-asyncio

pytest_asyncio/plugin.py, tests/test_simple.py
Asyncio doesn't get the results of tasks that fail with exceptions that
don't subclass `Exception` (like pytest's `Skipped`) in
`run_until_complete`. This leads to asyncio logging noisily warning when
pytest's skip functionality is mixed with this plugin.
This fixes this error, and adds a test.
Fixes #123.
=> No warning on skip in asyncio

setup.py, tests/test_hypothesis_integration.py, tests/test_subprocess.py
This PR contains 3 changes:
* Fix for running test_subprocess on windows by following instructions on https://docs.python.org/3.7/library/asyncio-subprocess.html#creating-subprocesses
* Change event_loop-fixture to module-scope in hypothesis tests, fixes #145 
* Change setup.py max version of pytest to avoid failures because of changes in 5.4.0 until #141 merged. It should be reverted in that PR.
=> Fix unittests and add max supported pytest version

README.rst, pytest_asyncio/plugin.py, tests/conftest.py, tests/multiloop/conftest.py
`@pytest.yield_fixture` is deprecated since pytest-3.0, see:
https://docs.pytest.org/en/latest/yieldfixture.html
=> Replace yield_fixture() by fixture()

pytest_asyncio/plugin.py, setup.py
This fixes https://github.com/pytest-dev/pytest-asyncio/issues/141.
=> plugin: Use pytest 5.4.0 new Function API

.travis.yml, setup.py, tests/conftest.py, tests/test_hypothesis_integration.py, tests/test_simple.py, tests/test_simple_35.py, tests/test_subprocess.py, tox.ini
This is a (merge-conflict free) rebase and squash of #133 with proper attribution to @asvetlov.
Unblocks #150
Closes #133
Fixes #129
=> Test on Python 3.8, drop 3.3 and 3.4

pytest_asyncio/plugin.py, tests/test_simple.py
Resolves #154, resolves #157, resolves #158 
Also adds unittests for the use case.
Not ready for merge, breaks `test_asyncio_marker_without_loop`, which was added in #64.
https://github.com/pytest-dev/pytest-asyncio/blob/a7e5795335b823b4d58bb6b38b6e653f0e0d35b0/tests/test_simple.py#L116-L128
Discussion for possible fix of broken test below
=> Fix event_loop is run after other fixtures

README.rst, pytest_asyncio/plugin.py, tests/conftest.py, tests/test_dependent_fixtures.py
Factories in pytest usually have a scope greater than 'function' to allow
one use the same factory within bigger scopes. Let us allow
unused_tcp_port_factory to be used throughout the same session scope.
This will allow other session-scoped factories depend on
unused_tcp_port_factory without getting a "ScopeMismatch" error.
=> plugin: Set unused_tcp_port_factory scope to 'session'

.github/workflows/main.yml
`3.10-dev` is no longer required, because `3.10` and `3.10.1` are released.
=> Use `python@3.10` in CI

README.rst, pytest_asyncio/plugin.py, tests/respect_event_loop_policy/conftest.py, tests/respect_event_loop_policy/test_respects_event_loop_policy.py
My understanding is that everyone is happy, if the event loop policy remains unaltered. I think I found a way to get rid of the code that resets the event loop policy.
Here is my understanding of the problem:
We need to make sure that each test case runs in an isolated fashion. Therefore, the `event_loop` fixture provides a fresh event loop and is automatically applied to all marked tests. When the fixture goes out of scope, it closes the event loop. Subsequent test cases would run into the following error:
```
RuntimeError: Event loop is closed
```
This is prevented a dedicated [fixture teardown](https://github.com/pytest-dev/pytest-asyncio/blob/4e2e6bd16682f6d3f8597cf5d7a86521a847e7ba/pytest_asyncio/plugin.py#L75-L80) prodecure. The teardown sets the event loop policy to `None`, which …
=> Teardown of the event_loop fixture no longer replaces the event loop policy

pytest_asyncio/plugin.py
`transfer_markers` was removed in Pytest 4.1. The minimum required pytest version for pytest-asyncio is currently v5.4.0. That means that `transfer_markers` is always a no-op.
=> Remove use of obsolete transfer_markers during test collection phase

.github/workflows/main.yml, README.rst, setup.py, tox.ini
CPython 3.6 reached end-of-life on 2021-12-23 [1]. Future releases of pytest will no longer support Python 3.6 [2].
We should consider dropping support for unmaintained Python versions.
[1] https://www.python.org/dev/peps/pep-0494/
[2] https://github.com/pytest-dev/pytest/pull/9437
=> Drop support for Python 3.6

.gitignore, pytest_asyncio/plugin.py, setup.py, tests/test_flaky_integration.py
When using [flaky](https://github.com/box/flaky) along with `pytest-asyncio`, for instance,
```python
@flaky.flaky(3)
@pytest.mark.asyncio
async def test_errors():
raise ValueError
```
when the first attempt failed, the second attempt will raise `RuntimeError: Event loop is closed` (given https://github.com/box/flaky/issues/166). The reason is that the wrapper https://github.com/pytest-dev/pytest-asyncio/blob/6ec76477061ea14394cadbf2cef673b04971ef4d/pytest_asyncio/plugin.py#L185 will be called twice in  `pytest_pyfunc_call` and the previous closed loop is still used. The resolution is to record the original function and wrap the original function every time.
Fixes #178
=> Resolve event loop closed issue when trying a second attempt with `flaky`

pytest_asyncio/plugin.py, setup.py
`setup.py` is also reformatted for the sake of uniformness.
=> Reformat with black

.pre-commit-config.yaml, LICENSE, Makefile, README.rst, pytest_asyncio/__init__.py, pytest_asyncio/plugin.py, setup.cfg, setup.py, tests/async_fixtures/test_async_fixtures_with_finalizer.py, tests/hypothesis/test_base.py, tests/hypothesis/test_inherited_test.py, tests/multiloop/conftest.py, tests/respect_event_loop_policy/test_respects_event_loop_policy.py, tests/sessionloop/conftest.py, tests/test_asyncio_fixture.py, tests/test_dependent_fixtures.py, tests/test_simple.py, tests/test_subprocess.py, tox.ini
Install hooks: `make install`
After that, `git commit ...` runs registered hooks from `.pre-commit-config.yaml` to committed files.
To skip hooks please use `git commit --no-verify ...`
The set of hooks can be adjusted, I've applied a configuration that I have for other projects.
=> Setup pre-commit hooks and reformat code

.github/workflows/main.yml, tools/get-version.py, tox.ini
The release is created on git tag pushing.
After linters and tests passed, the deploy stage is starting to wait for release approval.
@pytest-dev/pytest-asyncio-admin can approve. If nobody approved the release in 1 day -- deployment is discarded.
After the approval, we have 15 minutes timer for starting the deployment. During these 15 mins we the deployment task can be cancelled (just in case the deployer missed something).
The new release is pushed on PyPI (using generated PyPI upload token with `pytest-asyncio` scope) and on GitHub (visible as GitHub release).
Tag naming: as usual.
`v0.16`, `v0.17`  etc means final releases.
`v0.17a0` means *0.17 alpha 0* release.
`.post` releases are supported but please avoid them -- Dependabot uses SemVer; SemVer handles it as pre-release. Better to …
=> Release process automation

.github/dependabot.yml, .github/workflows/main.yml, .pre-commit-config.yaml
Default `yamlfmt` style is wider than I usually use.
The proposed PR suggests a much denser format.
=> Alternative yamlfmt settings

README.rst, pytest_asyncio/plugin.py, tests/hypothesis/test_base.py
The option `--asyncio-mode=auto` marks all async functions with the `asyncio` mark during the collection phase. However, when pytest collects the Hypothesis test, the `@given` decorator has already been applied and the Hypothesis test function is no longer a coroutine.
This commit extends the `pytest_pycollect_makeitem` hook to mark Hypothesis tests whose function body is a coroutine.
Closes #258
I was uncertain whether to add  the tests to the auto mode tests or to the Hypothesis tests. I eventually decided to add them to the tests for the Hypothesis integration. Rather than using `pytester` I added some assertions so the tests would fail in case we ever change `asyncio_mode` to something other than auto. Let me know what you think of this.
=> Fix auto marking of async hypothesis tests in auto mode

README.rst, pytest_asyncio/plugin.py, tests/test_event_loop_scope.py
=> Don't close event loop if the loop doesn't exist

Makefile, README.rst, pytest_asyncio/plugin.py, setup.cfg, tox.ini
Type checking is rough, better checks require not released yet pytest 7.0 at least.
Tests are not typed to don't pollute this big enough PR.
They can be typed later.
Fixes #198
=> Provide typing info

pytest_asyncio/plugin.py, setup.cfg
typing.Literal is available since Python 3.8.  Use it instead of
requiring typing-extensions for systems that no longer have Python 3.7.
=> Require typing-extensions on py<3.8 only

pytest_asyncio/plugin.py
The fixture injection is not needed, pytest 6.1.0+ works fine with using `request` argument from `pytest_fixture_setup()` hook.
=> Code cleanup: drop 'request' argument from async fixtures

README.rst, pytest_asyncio/plugin.py, tests/async_fixtures/test_parametrized_loop.py
Assume we have a parametrized `event_loop` fixture that provides both `asyncio` and `uvloop` event loops:
```
@pytest.fixture(scope="module", params=[asyncio.new_event_loop, uvloop.new_event_loop])
def event_loop(request):
loop = request.param()
yield loop
loop.close()
```
The PR fixes async fixtures creation to support such parametrization.
If shifts an async fixture function wrapping from fixture setup stage to tests collection stage.
`pytest` has no dedicated fixture collection hook (yet), the PR collects fixtures in `pytest_pycollect_makeitem` hooks.
The native pytest's fixtures manage uses a similar approach internally.
~As a side effect, tests execution is slightly faster. Async-sync wrapper is installed once per fixture definition, not on every fixture call. The boost is visible …
=> Support parametrized event_loop fixture

pyproject.toml, setup.cfg, tox.ini
`pyproject.toml` should use `setuptools_scm[toml]` dependency.
In turn, bare `setuptools_scm` should be dropped from `setup.cfg` `setup_requires` section.
@webknjaz suggested the change for another aio-libs project.
=> Fix setuptools_scm configuration

setup.cfg
We only use `typing_extensions` for the `Literal` type, which is available [starting from version `3.7.2`](https://github.com/python/typing/blob/1be6269634bec97d58d68cc1243359118373580a/typing_extensions/src_py3/typing_extensions.py#L129), so we don't necessarily need `typing_extensions>=4.0`
=> Relax dependency on typing-extensions

README.rst
Is there anything that's holding us back from releasing the current changes on master as v0.18?
Apparently, the current version on `master` fixes bugs for some users (e.g. #280).
=> Prepare release of v0.18.0

README.rst, pytest_asyncio/plugin.py, tests/test_asyncio_fixture.py
The function `_preprocess_async_fixtures` does nothing if the fixture is not an async function. The change simply prepares all async fixtures of a test regardless of whether the test is an async function or not.
Do you see any harm in doing so?
This should fix the issue encountered in #286.
=> Fix regression that prevents async fixtures from working in sync tests

README.rst, pytest_asyncio/plugin.py
This fixes a compatibility issue with Hypothesis 6.39.0.
No new test case was added, because the existing unit tests were already failing (see https://github.com/pytest-dev/pytest-asyncio/runs/5380149531)
Closes #302
=> Add positional arguments to the synchronous test function wrapper.

.github/workflows/main.yml, tox.ini
The tox "lint" target expects Python 3.10 to be installed, but CI only installs Python 3.9. The `skip_missing_interpreters` configuration caused the "lint" workflow in CI to exit successfully, even though no linting was performed.
This PR:
- Removes the `skip_missing_interpreters` to prevent silent errors in the future.
- Installs the required Python version during the lint workflow
- Removes tox's "lint" environment from the set of "3.9" environments of a GitHub actions run.
Linting is performed explicitly in a separate workflow and does not need to be run as part of the Python 3.9 tests. Additionally, linting currently expects Python 3.10 and will fail during the Python 3.9 test run. 
- Fixes a bug that prevented mypy to be installed correctly for tox's "lint" environment
The lint …
=> Fix CI linting workflow

CHANGELOG.rst, pytest_asyncio/plugin.py, setup.cfg, tests/loop_fixture_scope/conftest.py, tests/loop_fixture_scope/test_loop_fixture_scope.py, tests/test_subprocess.py, tests/trio/test_fixtures.py
This fixes a bug that breaks compatibility with pytest_trio (see #298).
The PR:
- Adds pytest-trio to the test dependencies.
- Removes test with obsolete "forbid_global_loop".
forbid_global_loop was an option to `pytest.mark.asyncio` which was removed in v0.6.0. The two subprocess tests are otherwise identical. Therefore, one of the tests was removed along with the obsolete option.
- Fixes a bug that causes a package-scoped event_loop fixture to leak into other tests.
The expected behaviour is that the `event_loop` fixture defined in `tests/sessionloop/conftest.py` is torn down when all tests in `tests/sessionloop` are complete. Running the tests with the pytest option `--setup-show` pointed out that the fixture is torn down at the end of the test session, instead. This is an unintended …
=> Do not try to initialize async fixtures without explicit asyncio mark in strict mode

.github/workflows/main.yml, CHANGELOG.rst, setup.cfg, tox.ini
* Updates Tox and CI to run tests on Python 3.11
* Adjust changelog and Trove classifiers
=> Python 3.11 support

README.rst
* Removed contradictory information on whether the loop from the `event_loop` fixture will be available as the global event loop
* Replaced example of custom event loop with an example of redefining the scope of the event_loop fixture
* Added recommendation to use a custom event loop policy rather than redefining the `event_loop` fixture
Closes #288
=> Clarify documentation of event_loop fixture

CHANGELOG.rst, README.rst, pytest_asyncio/plugin.py
Fixes #293
It's looking like a critical mass of projects have set `asyncio_mode=` if they need it, and an increasing number of projects are getting compatibility issues where they set `filterwarnings=error`, do not use `pytest-asyncio`, but are installed into an environment with it already.
In addition pytest has now deprecated returning not-None values https://docs.pytest.org/en/latest/deprecations.html#returning-non-none-value-in-test-functions and so in a future version test suites returning Coros will fail, rather than pass with a warning
=> opt into strict mode by default

CHANGELOG.rst, pytest_asyncio/plugin.py
If i'm off base here, feel free to close this...
but in my struggles to get my plugin working with pytest-asyncio, i kept noticing this holder check; and i couldn't possibly fathom how a ` fixturedef` would come to **be** this `_HOLDER` dict.
but it would make a lot more sense if the intent here was to avoid reexecuting the logic further down, if you already have classified that fixturedef previously.
=> Perform `in` (rather than `is) check against cached fixturedefs

CHANGELOG.rst, pytest_asyncio/plugin.py
The last v6 release of pytest was v6.2.5 on 2021-08-29. People have had more than a year to upgrade to pytest 7. It is time to sunset support for pytest 6.
=> Add deprecation warning for pytest < 7

pytest_asyncio/plugin.py
Pytest-asyncio essentially performs custom collection logic in `pytest_pycollect_makeitem`. This PR splits up the handling of async fixtures and async tests during test collection, renames a couple of thins, and extracts more fine-grained functions from `_preprocess_async_fixtures`. The goal of this PR is to make the code easier to understand.
This is a result of my investigation into #204.
=> Refactor pytest_pycollect_makeitems

CHANGELOG.rst, pytest_asyncio/plugin.py, tests/test_pytest_min_version_warning.py
This PR fixes an issue in the check for the pytest version. The changes prevent a warning about an outdated version of pytest to be emitted when the most recent version of pytest is installed.
Fixes #430.
=> Do not warn about outdated pytest version when pytest>=7 is installed

setup.cfg
Use `license_files` instead of `license_file` in `setup.py` to fix the following warning:
> The license_file parameter is deprecated, use license_files instead.
=> Fix setuptools deprecation warning for license_file

CHANGELOG.rst, dependencies/default/constraints.txt, pytest_asyncio/plugin.py, tests/test_simple.py
Pytest 7.2 introduces some deprecations which cause warnings when running the pytest-asyncio test suite.
Pytest now warns about the use of deprecated `@pytest.mark.tryfirst` and about tests that return a value different from `None`. The warnings were addressed accordingly so that the tests pass again.
=> Bump to pytest 7.2.0

CHANGELOG.rst, pytest_asyncio/plugin.py, tests/async_fixtures/test_async_fixtures.py, tests/async_fixtures/test_async_gen_fixtures.py
When passed a _bound_ fixture method, re-bind that method to the currently active instance.
The implementation follows how [pytest handles bound fixtures](https://github.com/pytest-dev/pytest/blob/2f33ea87c8d303c3439655eb2bea24483bffde5e/src/_pytest/fixtures.py#L1086-L1110), including how it'll always bind any fixture when `fixturedef.unittest` is true, and otherwise only if the fixture wasn't already bound or if bound to a an instance of the same class or a subclass thereof.
Fixes #197
=> Handle bound fixture methods correctly

.pre-commit-config.yaml, pytest_asyncio/plugin.py, tests/test_pytest_min_version_warning.py
This PR updates all pre-commit hooks to the most recent versions.
This fixes an issue that causes the CI pipeline to fail, due to the move of flake8 from GitLab to GitHub and the subsequent URL change (see https://github.com/PyCQA/flake8/pull/1305).
The update of shed causes changes in the ordering of some Union types. These should not break anything, though.
=> Update pre-commit hooks

docs/Makefile, docs/make.bat, docs/source/concepts.rst, docs/source/conf.py, docs/source/index.rst, docs/source/reference.rst, docs/source/support.rst, setup.cfg
This PR creates a stand-alone HTML documentation using Sphinx and ReStructuredText.
The structure roughly follows the [Diátaxis](https://diataxis.fr/) documentation framework in that it divides the content into four categories. Pytest-asyncio doesn't have tutorials and how-to guides at the moment, so these categories are missing. The _Explanation_ category was named _Concepts._ The documentation contains a supplementary section about how users can get support for pytest-asyncio.
Most contents of the stand-alone documentation were extracted from the README. However, the contents have been restructured and rephrased to fit into the new structure.
The docs can be built by entering the _docs_ folder and running `make html`.
@asvetlov @Tinche I would like to add you to the corresponding …
=> Stand-alone documentation

CHANGELOG.rst, pytest_asyncio/plugin.py
Pytest-asyncio fixture setup currently uses `get_event_loop` to clean up loops that don't correspond to the loop returned by the `event_loop` fixture. Starting with CPython 3.10.9 and 3.11.1 the call to get_event_loop emits a DeprecationWarning when function is called, but no event loop exists. This warning bubbles up and shows in test runs of library users. If the users have enabled `-W error` their tests will fail due to a warning in pytest-asyncio.
This patch ignores the DeprecationWarning in the fixture setup. This is a temporary solution to restore compatibility with the respective CPython patch releases.
Addresses #460
=> [fix] Prevent DeprecationWarning about existing event loops to bubble up into user code

.github/workflows/main.yml, tox.ini
Python 3.11 has been released. The pipeline currently uses the `3.11-dev` environment, which is no longer available. As a result  the CI build for CPython 3.11 is skipped.
=> Fix Python 3.11 CI environment

.github/workflows/main.yml, Makefile, tox.ini
Some code in pytest-asyncio is specific to certain versions of the Python interpreter. Therefore, the code coverage can be different for tests runs with different interpreters. Currently, the CI pipeline does not accommodate this fact.
This PR changes coverage data to be generated by each CI environment during the test runs. The different coverage results are combined in the check step just before uploading them to codecov.
The obsolete tox environment "coverage-report" has been removed.
The mypy command line option `--show-error-codes` has been removed, as showing error codes [is the default behavior](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-hide-error-codes).
This change addresses some of the deprecation warnings in the CI described in #429.
=> Combine coverage data for all interpreter versions

.github/workflows/main.yml, tools/get-version.py, tox.ini
The ::set-output command has been deprecated in favor of redirecting the output to a file. [0]
This patch adjusts _get-version.py_ to the new output syntax.
Unfortunately, `tox -qq` is no longer able to silences the summary output. Therefore, the get-version script is executed directly in the environment on the pipeline right after pytest-asyncio is installed.
[0] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Closes #429
=> Remove use of deprecated ::set-output GitHub command

.github/workflows/main.yml, .pre-commit-config.yaml, Makefile, tox.ini
This changeset adds mypy as a pre-commit hook. As a result, the pipeline can simply run pre-commit and we can get rid of the `make lint` target and the `tox -e lint` environment.
This patch also contains a couple of clean-ups to the CI pipeline.
=> Add mypy as pre-commit hook

README.rst
The README doesn't provide an easy way to find the docs :)
=> Add documentation link after migration to docs

docs/source/reference/changelog.rst, pytest_asyncio/plugin.py, tests/test_event_loop_fixture_finalizer.py
`asyncio.get_event_loop()` will effectively become an alias to `asyncio.get_running_loop()` in future Python versions. [0] As a result, pytest-asyncio will no longer be able to retrieve the current loop and close it for the user.
This PR raises a deprecation warning when the event_loop fixture is torn down and the current loop is unclosed. This will hopefully nudge users towards correct event loop handling and prevent breakage of their tests when pytest-asyncio removes the use of get_event_loop().
I think the [previous PR](https://github.com/pytest-dev/pytest-asyncio/pull/492) didn't go far enough with emitting a ResourceWarning, because ResourceWarnings are not displayed by default.
[0] [Deprecate get_event_loop()](https://github.com/python/cpython/issues/83710)
=> Deprecate closing of existing loops

.github/workflows/main.yml, tox.ini
This should make any incompatibilities visible earlier which, in turn, gives pytest-asyncio more time to adjust and react.
Closes #512
=> Tests are run against Python 3.12 (dev)

setup.cfg
Fixes the CI run for Python 3.12 until https://github.com/pytest-dev/pytest/issues/10977 is addressed in a release.
=> Ignore ast deprecation warnings on Python 3.12

docs/source/reference/changelog.rst, pytest_asyncio/plugin.py, tests/test_simple.py
Instead of a long INTERNALERROR> stack trace, output a proper error
message:
$ pytest -o asyncio_mode=True
=================== test session starts ====================
platform linux -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
ERROR: 'True' is not a valid asyncio_mode
See https://github.com/pytest-dev/pytest/issues/11083
=> Improve output with invalid asyncio_mode

setup.cfg
The issue has been addressed in pytest 7.4.0.
=> Remove obsolete warning filters

docs/source/reference/changelog.rst, docs/source/reference/fixtures.rst, pytest_asyncio/plugin.py
The fixture reference does not mention the fact that the scopes of _event_loop_ fixtures should not overlap. People may run into warnings and errors when they use overlapping scopes. (see #531)
This PR mentions the scoping limitation in the fixtures reference and extends the warning message for unclosed event loops to point users to a potential scoping issue.
Closes #531
=> Mention scoping limitation for event loop fixtures

docs/source/reference/changelog.rst, tests/test_simple.py
Previously, there have been some tests that try to assert compatibility with pytest.mark.xfail or pytest.skip. Those tests reported "xfailed" or "skipped" in the test suite.
This creates extra work for downstream packagers of pytest-asyncio if they want to run the unit test suite as part of the installation process.
This MR changes the tests to return "success" when they are successful. More specifically, the tests were changed to run  inside Pytester.
The test suite was also extended to test the corresponding behaviors in *auto* mode.
One unnecessary test case was removed.
=> All tests return "success" when they are successful

.github/workflows/main.yml, dependencies/default/constraints.txt, dependencies/default/requirements.txt, dependencies/pytest-min/requirements.txt, docs/source/reference/changelog.rst, pytest_asyncio/plugin.py, setup.cfg, tests/test_subprocess.py, tox.ini
We should do a release with the existing fixes and improvements (see other MRs) before dropping Python 3.7 support.
=> Remove support for Python 3.7

docs/source/reference/changelog.rst, docs/source/reference/fixtures.rst, pytest_asyncio/plugin.py, setup.cfg, tests/test_event_loop_fixture_finalizer.py, tests/test_event_loop_fixture_override_deprecation.py, tests/test_multiloop.py
Emit a DeprecationWarning when a test run by asyncio depends on a fixture named `event_loop` and that fixture definition is not the same as the one provided by pytest-asycnio.
Closes #631
=> Deprecate event loop fixture overrides

pytest_asyncio/plugin.py, tests/test_event_loop_fixture_finalizer.py
The existing code relies on the `__original_func` attribute to be _true_ on `FixtureDef.func`. For some reason, this is not always the case, even though the event_loop fixture sets the attribute in the function body.
This PR changes the warning to be triggered when the signature of the test function contains the `event_loop` argument, in which case the problem seems to go away..
=> Fix incorrect event loop fixture override warnings

docs/source/concepts.rst, docs/source/reference/fixtures/index.rst, pytest_asyncio/plugin.py, tests/async_fixtures/test_async_fixtures_with_finalizer.py, tests/async_fixtures/test_nested.py, tests/markers/test_class_marker.py, tests/test_event_loop_fixture_override_deprecation.py, tests/test_explicit_event_loop_fixture_request.py, tests/test_multiloop.py, tests/test_simple.py, tests/test_subprocess.py
=> Warn when event loop fixture is requested explicitly in async functions

dependencies/pytest-min/constraints.txt, docs/source/reference/changelog.rst, pytest_asyncio/plugin.py, tox.ini
Pytest-asyncio v0.22.0 makes use of `_pytest.mark.structures.get_unpacked_marks`. It explicitly passes the `consider_mro` keyword argument which has only been added in pytest v7.2. This lead to breakage for users of with pytest>=7.0,<7.2.
The error has not been uncovered by the test suite, due to wrong configuration of the _pytest-min_ tox environment.
This PR fixes the pytest-min test environment, adjusts the pinned dependencies for this environment, and issues the call to `get_unpacked_marks` in a way that is backwards compatible with older pytest versions.
Fixes #654
=> Restore compatibility with pytest>=7.0,<7.2

docs/source/how-to-guides/index.rst, docs/source/how-to-guides/multiple_loops.rst, docs/source/how-to-guides/multiple_loops_example.py, docs/source/how-to-guides/uvloop.rst, docs/source/reference/changelog.rst, docs/source/reference/fixtures/event_loop_policy_example.py, docs/source/reference/fixtures/event_loop_policy_parametrized_example.py, docs/source/reference/fixtures/index.rst, docs/source/reference/markers/class_scoped_loop_custom_policies_strict_mode_example.py, docs/source/reference/markers/class_scoped_loop_custom_policy_strict_mode_example.py, pytest_asyncio/plugin.py, tests/markers/test_class_marker.py, tests/markers/test_function_scope.py, tests/markers/test_module_marker.py
This PR introduces the new fixture _event_loop_policy._ The fixture returns an instance of an _asyncio.AbstractEventLoopPolicy_. By default, the fixture has _session_ (i.e. it is accessible by all tests) and returns the value of _asyncio.get_event_loop_policy()_.
Users can run pytest-asyncio tests with different types of event loops by redefining the fixture to return a different event loop policy. Parametrizing the fixture causes pytest-asyncio tests to be run once for each specified policy. This allows writing tests against multiple different types of event loops.
Although the concept of event loop policies is likely going to be [deprecated in CPython 3.13,](https://github.com/python/cpython/issues/94597) it was decided that this functionality is still going to land in pytest-asyncio. …
=> Introduce event_loop_policy fixture

docs/source/reference/markers/class_scoped_loop_with_fixture_strict_mode_example.py, pytest_asyncio/plugin.py, tests/async_fixtures/test_async_fixtures_with_finalizer.py, tests/hypothesis/test_base.py, tests/markers/test_class_scope.py, tests/markers/test_function_scope.py, tests/markers/test_module_scope.py, tests/markers/test_package_scope.py, tests/markers/test_session_scope.py, tests/test_event_loop_fixture_finalizer.py, tests/test_event_loop_fixture_override_deprecation.py, tests/test_explicit_event_loop_fixture_request.py
Fixes a bug that caused tests to run in the wrong event loop when requesting larger-scoped fixtures in a narrower-scoped test.
Previously, pytest-asyncio relied on marks applied to pytest Collectors (e.g. classes and modules) to determine the loop scope. This logic is no longer applicable for fixtures, because pytest-asyncio now relies on the asyncio mark applied to tests. As a result, fixtures were looking for an "asyncio" mark on surrounding collectors to no avail and defaulted to choosing a function-scoped loop.
This patch chooses the loop scope based on the fixture scope.
Resolves #658 
Resolves #670
=> Async fixtures request wrong event loop

pytest_asyncio/plugin.py, tests/test_doctest.py
This PR fixes a bug that caused internal pytest errors during test collection with doctests.
Pytest-asyncio attaches an event loop of a particular scope to each collector during pytest_collectstart. The implementation did not account for the fact that collectors may have specialized subclasses, such as DoctestModule. This caused a KeyError during a dictionary access, leading to an internal pytest error in the collection phase.
This patch changes the implementation of pytest_collectstart to account for subclasses of collectors.
Resolves #679
=> Address internal pytest error during collection of doctests

docs/source/concepts.rst, docs/source/concepts_function_scope_example.py, docs/source/concepts_module_scope_example.py, docs/source/how-to-guides/class_scoped_loop_example.py, docs/source/how-to-guides/index.rst, docs/source/how-to-guides/module_scoped_loop_example.py, docs/source/how-to-guides/package_scoped_loop_example.py, docs/source/how-to-guides/run_class_tests_in_same_loop.rst, docs/source/how-to-guides/run_module_tests_in_same_loop.rst, docs/source/how-to-guides/run_package_tests_in_same_loop.rst, docs/source/how-to-guides/run_session_tests_in_same_loop.rst, docs/source/how-to-guides/session_scoped_loop_example.py
This PR extends the docs to explain the new scoped-loop idea in the _concepts_ section and adds how-tos for running loops in a certain scope.
Resolves #676
Resolves #677
=> How tos for loop scopes

.github/workflows/main.yml
This should fix #699 and prevent the warning.
Closes #699
=> [fix] Change `packages_dir` to `packages-dir`

docs/source/reference/changelog.rst, pytest_asyncio/plugin.py, tests/markers/test_module_scope.py, tests/markers/test_session_scope.py
Fixes a bug that caused event loops to be closed prematurely when using async generator fixtures with class scope or wider in a function-scoped test.
The fixture setup of the "event_loop" fixture closes any existing loop. The existing loop could also belong to a pytest-asyncio scoped event loop fixture. This caused async generator fixtures using the scoped loop to raise a RuntimeError on teardown, because the scoped loop was closed before the fixture finalizer could not be run. In fact, everything after the async generation fixture's "yield" statement had no functioning event loop.
The issue was addressed by adding a special attribute to the scoped event loops provided by pytest-asyncio. If this attribute is present, the setup code of the "event_loop" fixture will not close the loop. This …
=> Prevent premature closing of scoped event loops

docs/source/reference/changelog.rst, pytest_asyncio/plugin.py, tests/test_import.py
There have been numerous bug reports related to a pytest INTERNALERROR triggered during test collection.The root cause is the installation of the scoped event loop fixture which triggers module imports during `pytest_collectstart`. This specific hook runs before the actual collection phase and is not equipped to deal with this kind of import errors.
This PR monkey patches each Module.collect call and prepends a statement that installs the scoped event loop as part of the _collect_ call. This delays module imports until the collection phase where pytest deals with them properly.
Closes #713 
Closes #719
=> Address internal pytest errors during collection

docs/source/reference/changelog.rst, pytest_asyncio/plugin.py, tests/markers/test_package_scope.py, tests/test_import.py
#729 describes an issue where pytest-asyncio imports packages (i.e. `__init__.py` modules) which are not imported without pytest-asyncio. The imported packages could be test packages and non-test packages. This leads to two issues:
1. The import happens in the `pytest_collectstart` hook just before the collection phase. Pytest isn't equipped to deal with import errors or test skips in this hook, so the import can trigger an INTERNALERROR which aborts the test run completely.
2. Importing packages that are unrelated to the test run may trigger ImportErrors or ImportWarnings. The greedy import behaviour can even cause issues just by changing the import order (refer to  due to a change in the import order (refer to [this comment](https://github.com/pytest-dev/pytest-asyncio/issues/729#issueco …
=> Prevent import of unrealted packages during test collection

dependencies/default/requirements.txt, setup.cfg
Pytest 8 made some changes to its test collection and pytest-asyncio currently isn't compatible with those changes.
see https://github.com/pytest-dev/pytest-asyncio/issues/737
=> [build] Constrain the maximum supported pytest version to pytest <8.

.github/workflows/main.yml, pytest_asyncio/plugin.py, tests/test_subprocess.py
pytest-asyncio v0.23.4a0 introduced "virtual modules". These are temporary files in Python packages which contain a fixture definition. The files are removed after the virtual module was collected by pytest.
The use of temporary files has platform-specific behavior. Apparently, pytest opens the NamedTemporaryFile again, which causes issues on Windows. The [the docs](https://docs.python.org/3.12/library/tempfile.html#tempfile.NamedTemporaryFile) describe the problem and possible mitigations:
> Opening the temporary file again by its name while it is still open works as follows:
>     On POSIX the file can always be opened again.
>     On Windows, make sure that at least one of the following conditions are fulfilled:
>         * delete is false
>         * additional open shares delete …
=> Fixes a bug that breaks virtual modules on Windows

docs/source/reference/changelog.rst, pytest_asyncio/plugin.py
This PR changes the way package-scoped fixtures are registered. Pytest-asyncio no longer creates temporary Python modules (aka "virtual modules") with fixture definitions during collection time. Some setups seem to rely on a fixed list of collected files (see https://github.com/pytest-dev/pytest-asyncio/issues/729#issuecomment-1887800329).
This PR also limits the impact of pytest-asyncio's collection changes for scoped event loops. The plugin no longer tries to install scoped event loops in unknown collector types.
=> No virtual modules & No scoped loops for unknown collectors.

.pre-commit-config.yaml, docs/source/reference/changelog.rst, pytest_asyncio/__init__.py, pytest_asyncio/plugin.py, tests/async_fixtures/test_async_fixtures_scope.py, tests/hypothesis/test_base.py, tests/loop_fixture_scope/test_loop_fixture_scope.py, tests/markers/test_class_scope.py, tests/test_simple.py, tests/test_skips.py, tests/test_subprocess.py
pytest-asyncio-0.23.4a2 suffers from a problem that causes tests to be skipped during the collection phase as described in 
https://github.com/pytest-dev/pytest-asyncio/issues/729#issuecomment-1900518338
It turns out the tests were skipped, because the test suite in question used test packages and the first module inside the package issued a `pytest.skip` statement. The custom collection function for packages introduced in pytest-asyncio-0.23.4a2 tries to access `Module.obj` which triggers the `pytest.skip` and causes the collection of the package to abort.
Rather than trying to access `Module.obj`, this patch adds a package-scoped fixture to a stack each time a package is collected. The first module inside each package tries to pop an item from the stack and adds the popped loop fixture …
=> Prevent collection issues with skip statements inside packages

docs/source/reference/changelog.rst, pytest_asyncio/plugin.py, tests/markers/test_class_scope.py, tests/markers/test_function_scope.py, tests/markers/test_module_scope.py, tests/markers/test_package_scope.py, tests/markers/test_session_scope.py
Pytest-asyncio still uses *asyncio.get_event_loop()*. There are plans to move away from it, but *get_event_loop* is required to maintain compatibility between scoped event loops and loop fixture overrides.
This may lead to instances where the first asyncio test in a test suite emits a *DeprecationWarning*, which bubbles up to the user's test suite.
This PR silences the warning until pytest-asyncio no longer needs to manipulate the event loop directly.
closes  #757
=> Prevent DeprecationWarning from reaching user code

docs/source/how-to-guides/run_session_tests_in_same_loop.rst, docs/source/how-to-guides/session_scoped_loop_example.py, docs/source/how-to-guides/test_session_scoped_loop_example.py
Fixes the example showing how to run all tests in a session-scoped loop.
The change also adds a warning that the code snippet overrides all manually applied marks in strict mode and adds tests verifying the correctness of the example.
The underlying problem was discovered in https://github.com/pytest-dev/pytest-asyncio/issues/705#issuecomment-1956834467
=> Fix example for all tests in session loop

docs/source/reference/changelog.rst, pytest_asyncio/plugin.py
Since pytest 8.2 (still in development) unittest and regular will behave the same, so unittest special handling is no longer needed.
I also added two unrelated cleanup commits I noticed, if you prefer I can remove them.
=> Fix compatibility with pytest 8.2 FixtureDef.unittest removal

docs/source/reference/changelog.rst, pytest_asyncio/plugin.py
Backported #800 to the 0.21.1 tag
This unblocks all users stuck with 0.21.1 due to #706
As is, this PR can't be merged. A new branch, created from tag 0.21.1, must be created first. Then the base branch of this PR must be changed to that branch
I've run a few test suites locally and these changes work fine: any feedback is welcome
=> Made 0.21.1 compatible with pytest 8.2.0

docs/source/reference/changelog.rst
=> Cherry-pick changelog entry for v0.21.2

docs/source/reference/changelog.rst, pytest_asyncio/plugin.py, tests/hypothesis/test_base.py, tests/markers/test_function_scope.py, tests/markers/test_module_scope.py, tests/modes/test_strict_mode.py, tests/test_asyncio_mark.py, tests/test_event_loop_fixture_finalizer.py, tests/test_event_loop_fixture_override_deprecation.py, tests/test_explicit_event_loop_fixture_request.py
=> Fix duplication of markers in async tests

.pre-commit-config.yaml
Removes the actionlint-docker pre-commit hook, which requires Docker to be set up on the development machine. Given that the pre-commit hooks already lint yaml files and that the GitHub actions are run for every PR, the Docker dependency seems unreasonable.
closes #595
=> Remove development dependency on Docker

docs/source/reference/changelog.rst, pytest_asyncio/plugin.py, tests/markers/test_invalid_arguments.py
This PR implements error checking for the arguments of `mark.asyncio`.
An ValueError with a helpful message is raised when unexpected arguments are passed. 
This should fix issue #812.
=> Check marker arguments

.github/workflows/main.yml, .pre-commit-config.yaml
Removes pre-commit steps from the GitHub actions workflow, because the hooks are now executed by pre-commit.ci.
=> Clean up GitHub actions

dependencies/default/requirements.txt, dependencies/pytest-min/constraints.txt, dependencies/pytest-min/requirements.txt, docs/source/reference/changelog.rst, pytest_asyncio/plugin.py, setup.cfg, tests/async_fixtures/test_shared_module_fixture.py, tests/test_is_async_test.py
Caching of fixture preprocessing is now also keyed by event loop id, sync fixtures can be processed if they are wrapping a async fixture, each async fixture has a mapping from root scope name to fixture id that is now used to dynamically get the event loop fixture.
3 tests fail for me locally, 2 more are flaky, some of these fail without my changes.
I'm note sure if I'm conflating fixture and loop scope and if that is contributing to the failed tests.
I feel like I have not written the clearest code but can only see a broader refactoring as a way out of that and would like feedback if this approach is even something worth doing before undertaking that.
This fixes #862.
@seifertm
=> Preprocess async fixtures for each event loop

.readthedocs.yaml, docs/source/conf.py
Fixes #628 
Using `importlib` to populate the version field in `conf.py`
=> Derive project version using importlib

.github/workflows/main.yml, .gitignore, Makefile, setup.cfg
Coverage writes reports to ".coverage" by default. The GitHub action "upload-artifact" no longer includes hidden files by default. This patch changes the coverage file name to a non-hidden file path.
This fixes the failing CI pipeline for pull requests.
=> Address invisible hidden files in artifact upload action

pytest_asyncio/plugin.py
=> Switch to `inspect.iscoroutinefunction` over `asyncio.iscoroutinefunction`

docs/reference/changelog.rst, pytest_asyncio/plugin.py, tests/modes/test_strict_mode.py
partially fixes https://github.com/pytest-dev/pytest/issues/10839, see https://github.com/pytest-dev/pytest/issues/10839#issuecomment-2355427134
It got a bit messy to implement, and relies on non-public API in `_fixtureinfo`, so I'm not 100% that this is the best way to approach it. Another approach would be to try and catch this on collection, but then you end up having to handle overriding fixtures and the like.
It's also *possible* that this breaks tests for end users, but if they really do want an unawaited object from a fixture they can resolve it in various ways by returning an `Awaitable` from their fixture.
=> warn if asyncio test requests async pytest fixture in strict mode

docs/reference/changelog.rst, pytest_asyncio/plugin.py, tests/markers/test_invalid_arguments.py
Ensures that when a wrong argument is passed, the non-deprecated `loop_scope` keyword arg is recommended.
=> Rename 'scope' to 'loop_scope' in error message

docs/reference/changelog.rst, pytest_asyncio/plugin.py
confirmed verbose output displays correct name:
asyncio: mode=Mode.AUTO, asyncio_default_fixture_loop_scope=function
file __version__ not present and I don't understand the issue described in setup.cfg
guessed version in changelog.rst with totally random date (my birthday)
=> display full param name asyncio_default_fixture_loop_scope

docs/reference/markers/index.rst
before that: docs claimed (erroneously) the opposite of the actual (and intended) behavior.
=> docs: describe when UsageError is raised for loop_scope="class" marker

docs/reference/changelog.rst, pytest_asyncio/plugin.py, tests/async_fixtures/test_async_fixtures_contextvars.py
The approach I've taken here is to inspect the context after running the fixture setup task and copy any changed values out into the test's ambient context. When we run the finalizer to tear down the fixture, we then reset the modified variables.
Some limitations:
- This requires Python 3.11 or higher (for https://github.com/python/cpython/issues/91150).
- Because we have to iterate over the fixture context to copy out changes, this approach may be slow for fixtures that run in contexts with a large number of variables.
Fixes pytest-dev/pytest-asyncio#127.
=> Maintain contextvars between fixtures and tests

docs/reference/changelog.rst
This config option is arguably a new API surface, and it took me a fair bit of git archaeology to figure out from which version on I can use this config option.
This entry might save some users some time in the future :)
=> Mention `asyncio_default_fixture_loop_scope` in v0.24 changelog

pytest_asyncio/plugin.py
Changes a couple places to check asyncio_mode (cheap) before _is_asyncio_fixture_function
To fix https://github.com/pytest-dev/pytest-asyncio/issues/720
=> Speed-up test collection for larger codebases

docs/reference/changelog.rst, pytest_asyncio/plugin.py, tests/markers/test_mixed_scope.py, tests/test_event_loop_fixture_finalizer.py
Issue #950 describes a problem with tests that have mixed event loop scopes. When a function-scoped loop is executed in between two tests with wider loop scope, the tests after the function-scoped tests reference the wrong event loop.
This is caused by the implementation of the _event_loop_ fixture and its finalizers. This PR addresses the issue twofold:
1. It changes the implementation of the _event_loop_ fixture so that it properly restores the current event loop policy and event loop when the fixture is torn down.
2. It changes the _event_loop_ fixture finalizers to only close loops that were not created by pytest-asyncio. This prevents the finalizers from accidentally closing a module-scoped loop provided by the plugin, for example.
Fixes #950
=> Fix wrong event loop reference with mixed scoped tests

docs/reference/changelog.rst, docs/reference/fixtures/index.rst, docs/reference/markers/index.rst, pytest_asyncio/plugin.py
This PR changes the docs to reflect the fact that the _event_loop_ fixture is deprecated.
Additionally, it fixes the warning message that is emitted when users redefine the fixture and fixes a broken link in the docs.
Closes #964
=> Clarify event_loop fixture deprecation

docs/reference/changelog.rst, pytest_asyncio/plugin.py, tests/test_event_loop_fixture.py
#222 was closed, mentioning the issues being resolved in the yet-to-be-done #235, running with `-W error` in Python 3.13, currently fails when there are unclosed async generators. 
This is a minimally invasive fix, without attempting to behave like `asyncio.run` on shutdown in all other scenarios.
=> Call `loop.shutdown_asyncgens` before closing the event loop

docs/reference/changelog.rst, pyproject.toml, pytest_asyncio/plugin.py
If TypeVars are used in TypeAliases, they need to be passed along as well. Otherwise it's just interpreted as `Any` similar to all other generic type without subscripts.
This PR reworks the TypeAliases and TypeVars to properly type the `fixture` function.
=> Fix FixtureFunction TypeAlias and TypeVars

docs/reference/changelog.rst, pytest_asyncio/plugin.py, tests/test_event_loop_fixture.py
check `is_closed()` before calling cleanup methods and catch errors in cleanup to avoid problems
closes #1040
=> Avoid errors in cleanup when event loop is already closed

docs/concepts.rst
When reading the docs, it wasn't clear to me how to set asyncio's mode and I had to rely on looking at the source code. I thought it would be nice to expand the docs to be more explicit in this regard.
=> docs: specify how asyncio's mode can be set

pyproject.toml
[PEP 639](https://peps.python.org/pep-0639/) added support for SPDX license identifier.
Metadata diff
```diff
...
-License: Apache 2.0
+License-Expression: Apache-2.0
...
-Classifier: License :: OSI Approved :: Apache Software License
...
```
=> Update project metadata to use SPDX license identifier

.github/workflows/main.yml, docs/reference/changelog.rst, pyproject.toml
The changelog has previously been maintained manually. This lead to avoidable merge conflicts, because of changelog patches. Moreover, it increases the roundtrip time for contributions, because contributors generally don't adjust the changelog which forces the maintainers to ask for an explicit changelog entry.
This patch uses towncrier to collect changelog entries and compile them during the release process.
TBD: Enforce changelog entries
Previously, the release workflow attached the README as release notes. This is mostly unhelpful and results in length email notifications when a pytest-asyncio release is published.
This patch uses the annotation built Git tag as release notes. If the current build is not a Git tag, the compiled towncrier news fragments are published as release notes. …
=> Use Towncrier to Manage Changelog

changelog.d/+bd8f0ee6.changed.rst, docs/reference/markers/index.rst, pytest_asyncio/plugin.py, tests/markers/test_class_scope.py, tests/markers/test_package_scope.py
Historically, pytest-asyncio maintained one event loop fixture per pytest collector. This has changed in #1107 and pytest-asyncio only maintains one event loop per scope.
This PR removes obsolete management code related to having one loop per collector. In the process, this removes the restriction that a test marked with `asyncio(loop_scope="class")` or `asyncio(loop_scope="package")` has to be surrounded by a class or test. The new behavior is in line with pytest's scope argument to fixtures.
=> Simplify scoped loop fixture discovery

changelog.d/1025.added.rst, changelog.d/1106.removed.rst, changelog.d/1107.changed.rst, changelog.d/1112.changed.rst, changelog.d/630.fixed.rst, docs/reference/changelog.rst
This PR disassembles the v1.0.0a1 changelog into news fragments. This allows adding fragments to further pre-releases.
It adds an entry for the fix of #630 which can no longer be reproduced with v1.0.0a1.
=> Mention fix for 630 in release notes

.github/workflows/main.yml
=> Fix release note extraction from Git tag annotation

tests/modes/test_strict_mode.py
Async tests fail instead of skipping and warning with Pytest 8.4.0 if no suitable async plugin is installed[1]. Adjust expectation of these tests to pass the testsuite with Pytest 8.4.0.
Link: https://docs.pytest.org/en/stable/changelog.html#pytest-8-4-0-2025-06-02 # [1]
=> test: Adapt unmarked async tests in strict mode for pytest 8.4.0

changelog.d/+127.added.rst, changelog.d/+6aa3d3e0.added.rst, changelog.d/+6fe51a75.downstream.rst, changelog.d/+878.fixed.rst, changelog.d/200.added.rst, pyproject.toml, pytest_asyncio/plugin.py, tests/async_fixtures/test_async_fixtures_contextvars.py, tests/test_event_loop_fixture.py, tests/test_task_cleanup.py
Previously, pytest-asyncio used a combination of low-level asyncio functions to manage event loops. This patch replaces the low-level functions with the use of asyncio.Runner.
The runner takes care of cancelling remaining tasks at the end of its scope, avoiding errors about pending tasks. This also fixes an issue that caused RuntimeErrors in abanoned tasks that called functions which depend on a running loop.
Moreover, the use of asyncio.Runner and its backport allows backporting the propagation of contextvars from fixtures to tests to Python 3.9 and Python 3.10.
Supersedes #309
Closes #127 
Closes #200
Closes #878 
Partially addresses #1032
=> Replace event loops with asyncio.Runner

changelog.d/+b22c903a.fixed.rst, pytest_asyncio/plugin.py, tests/markers/test_function_scope.py
This is a refactoring patch aiming to simplify the logic of synchronizers in the code. It is best reviewed commit by commit.
=> Simplify synchronizers

changelog.d/980.added.rst, pytest_asyncio/plugin.py, tests/test_asyncio_debug.py
Add a config option and CLI option to use asyncio debug mode.
Closes #980
=> Add debug option

changelog.d/1198.fixed.rst, docs/reference/changelog.rst, pytest_asyncio/plugin.py, tests/modes/test_strict_mode.py
Was reading through the changelog and found this amusing brain fart I introduced in #979
Turns out I've contributed to way too many flake8-* projects x)
=> fix typos flake8-asyncio -> pytest-asyncio
